[workspace]
resolver = "2"
members = ["client", "server", "shared"]

[profile.wasm-release]
inherits = "release"
opt-level = "z"
lto = "fat"
codegen-units = 1

[profile.dev.package.rapier3d]
opt-level = 3